//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////
// Remere's Map Editor is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Remere's Map Editor is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//////////////////////////////////////////////////////////////////////

#ifndef RME_WXIDS_H_
#define RME_WXIDS_H_

// Enums

enum {
	SELECT_CURRENT_FLOOR,
	SELECT_ALL_FLOORS,
	SELECT_VISIBLE_FLOORS,
};

enum BrushShape {
	BRUSHSHAPE_CIRCLE,
	BRUSHSHAPE_SQUARE,
};

enum EditorMode {
	SELECTION_MODE,
	DRAWING_MODE,
};

// Window IDs
enum EditorActionID
{
	MENUBAR_NEW = wxID_HIGHEST + 1,
	MENUBAR_OPEN,
	MENUBAR_SAVE,
	MENUBAR_SAVE_AS,
	MENUBAR_CLOSE,
	MENUBAR_IMPORT_MAP,
	MENUBAR_EXPORT_MINIMAP,
	MENUBAR_RELOAD_DATA,
	MENUBAR_RECENT_FILES,
	MENUBAR_PREFERENCES,
	MENUBAR_EXIT,
	MENUBAR_UNDO,
	MENUBAR_REDO,
	MENUBAR_FIND_ITEM,
	MENUBAR_REPLACE_ITEMS,
	MENUBAR_SEARCH_ON_MAP_EVERYTHING,
	MENUBAR_SEARCH_ON_MAP_CONTAINER,
	MENUBAR_SEARCH_ON_MAP_WRITEABLE,
	MENUBAR_SEARCH_ON_MAP_DUPLICATED_ITEMS,
	MENUBAR_SEARCH_ON_SELECTION_EVERYTHING,
	MENUBAR_SEARCH_ON_SELECTION_CONTAINER,
	MENUBAR_SEARCH_ON_SELECTION_WRITEABLE,
	MENUBAR_SEARCH_ON_SELECTION_ITEM,
	MENUBAR_SEARCH_ON_SELECTION_DUPLICATED_ITEMS,
	MENUBAR_REPLACE_ON_SELECTION_ITEMS,
	MENUBAR_REMOVE_ON_SELECTION_ITEM,
	MENUBAR_SELECT_MODE_COMPENSATE,
	MENUBAR_SELECT_MODE_CURRENT,
	MENUBAR_SELECT_MODE_LOWER,
	MENUBAR_SELECT_MODE_VISIBLE,
	MENUBAR_AUTOMAGIC,
	MENUBAR_BORDERIZE_SELECTION,
	MENUBAR_BORDERIZE_MAP,
	MENUBAR_RANDOMIZE_SELECTION,
	MENUBAR_RANDOMIZE_MAP,
	MENUBAR_GOTO_PREVIOUS_POSITION,
	MENUBAR_GOTO_POSITION,
	MENUBAR_JUMP_TO_BRUSH,
	MENUBAR_JUMP_TO_ITEM_BRUSH,
	MENUBAR_CLEAR_INVALID_HOUSES,
	MENUBAR_CLEAR_MODIFIED_STATE,
	MENUBAR_CUT,
	MENUBAR_COPY,
	MENUBAR_PASTE,
	MENUBAR_EDIT_TOWNS,
	MENUBAR_EDIT_ITEMS,
	MENUBAR_EDIT_MONSTERS,
	MENUBAR_MAP_CLEANUP,
	MENUBAR_MAP_REMOVE_ITEMS,
	MENUBAR_MAP_REMOVE_CORPSES,
	MENUBAR_MAP_REMOVE_UNREACHABLE_TILES,
	MENUBAR_MAP_CLEAN_HOUSE_ITEMS,
	MENUBAR_MAP_STATISTICS,
	MENUBAR_VIEW_TOOLBARS_BRUSHES,
	MENUBAR_VIEW_TOOLBARS_POSITION,
	MENUBAR_VIEW_TOOLBARS_SIZES,
	MENUBAR_VIEW_TOOLBARS_INDICATORS,
	MENUBAR_VIEW_TOOLBARS_STANDARD,
	MENUBAR_TOGGLE_FULLSCREEN,
	MENUBAR_ZOOM_IN,
	MENUBAR_ZOOM_OUT,
	MENUBAR_ZOOM_NORMAL,
	MENUBAR_SHOW_SHADE,
	MENUBAR_SHOW_ALL_FLOORS,
	MENUBAR_GHOST_ITEMS,
	MENUBAR_GHOST_HIGHER_FLOORS,
	MENUBAR_HIGHLIGHT_ITEMS,
	MENUBAR_SHOW_INGAME_BOX,
	MENUBAR_SHOW_LIGHTS,
	MENUBAR_SHOW_GRID,
	MENUBAR_SHOW_EXTRA,
	MENUBAR_SHOW_CREATURES,
	MENUBAR_SHOW_SPECIAL,
	MENUBAR_SHOW_AS_MINIMAP,
	MENUBAR_SHOW_ONLY_COLORS,
	MENUBAR_SHOW_ONLY_MODIFIED,
	MENUBAR_SHOW_HOUSES,
	MENUBAR_SHOW_PATHING,
	MENUBAR_SHOW_TOOLTIPS,
	MENUBAR_SHOW_PREVIEW,
	MENUBAR_SHOW_WALL_HOOKS,
	MENUBAR_SHOW_PICKUPABLES,
	MENUBAR_SHOW_MOVEABLES,
	MENUBAR_WIN_MINIMAP,
	MENUBAR_WIN_ACTIONS_HISTORY,
	MENUBAR_NEW_PALETTE,
	MENUBAR_TAKE_SCREENSHOT,
	MENUBAR_SELECT_TERRAIN,
	MENUBAR_SELECT_DOODAD,
	MENUBAR_SELECT_ITEM,
	MENUBAR_SELECT_CREATURE,
	MENUBAR_SELECT_HOUSE,
	MENUBAR_SELECT_WAYPOINT,
	MENUBAR_SELECT_RAW,
	MENUBAR_FLOOR_0,
	MENUBAR_FLOOR_1,
	MENUBAR_FLOOR_2,
	MENUBAR_FLOOR_3,
	MENUBAR_FLOOR_4,
	MENUBAR_FLOOR_5,
	MENUBAR_FLOOR_6,
	MENUBAR_FLOOR_7,
	MENUBAR_FLOOR_8,
	MENUBAR_FLOOR_9,
	MENUBAR_FLOOR_10,
	MENUBAR_FLOOR_11,
	MENUBAR_FLOOR_12,
	MENUBAR_FLOOR_13,
	MENUBAR_FLOOR_14,
	MENUBAR_FLOOR_15,
	MENUBAR_DEBUG_VIEW_DAT,
	MENUBAR_GOTO_WEBSITE,
	MENUBAR_ABOUT,

	MAP_WINDOW_HSCROLL,
	MAP_WINDOW_VSCROLL,
	MAP_WINDOW_GEM,

	MAP_POPUP_MENU_CUT,
	MAP_POPUP_MENU_COPY,
	MAP_POPUP_MENU_COPY_POSITION,
	MAP_POPUP_MENU_PASTE,
	MAP_POPUP_MENU_DELETE,

	MAP_POPUP_MENU_COPY_TYPE_ID,
	MAP_POPUP_MENU_COPY_NAME,
	MAP_POPUP_MENU_BROWSE_TILE,

	MAP_POPUP_MENU_SWITCH_DOOR,
	MAP_POPUP_MENU_ROTATE,
	MAP_POPUP_MENU_GOTO,
	MAP_POPUP_MENU_COPY_DESTINATION,
	MAP_POPUP_MENU_SELECT_RAW_BRUSH,
	MAP_POPUP_MENU_SELECT_CREATURE_BRUSH,
	MAP_POPUP_MENU_SELECT_SPAWN_BRUSH,
	MAP_POPUP_MENU_SELECT_GROUND_BRUSH,
	MAP_POPUP_MENU_SELECT_DOODAD_BRUSH,
	MAP_POPUP_MENU_SELECT_DOOR_BRUSH,
	MAP_POPUP_MENU_SELECT_WALL_BRUSH,
	MAP_POPUP_MENU_SELECT_TABLE_BRUSH,
	MAP_POPUP_MENU_SELECT_CARPET_BRUSH,
	MAP_POPUP_MENU_SELECT_HOUSE_BRUSH,
	MAP_POPUP_MENU_PROPERTIES,

	CONTAINER_POPUP_MENU_ADD,
	CONTAINER_POPUP_MENU_INSPECT,
	CONTAINER_POPUP_MENU_REMOVE,

	EDIT_TOWNS_LISTBOX,
	EDIT_TOWNS_ADD,
	EDIT_TOWNS_REMOVE,
	EDIT_TOWNS_SELECT_TEMPLE,

	JUMP_DIALOG_TEXT,
	JUMP_DIALOG_LIST,

	REPLACE_DIALOG_FIND_TEXT,
	REPLACE_DIALOG_FIND_LIST,
	REPLACE_DIALOG_WITH_TEXT,
	REPLACE_DIALOG_WITH_LIST,

	MAP_STATISTICS_EXPORT_XML,

	MAP_WINDOW_FILE_BUTTON,

	PALETTE_ITEM_CHOICEBOOK,
	PALETTE_CHOICEBOOK,

	PALETTE_HOUSE_TOWN_CHOICE,
	PALETTE_HOUSE_LISTBOX,
	PALETTE_HOUSE_ADD_HOUSE,
	PALETTE_HOUSE_EDIT_HOUSE,
	PALETTE_HOUSE_REMOVE_HOUSE,
	PALETTE_HOUSE_BRUSH_BUTTON,
	PALETTE_HOUSE_SELECT_EXIT_BUTTON,

	PALETTE_WAYPOINT_LISTBOX,
	PALETTE_WAYPOINT_ADD_WAYPOINT,
	PALETTE_WAYPOINT_REMOVE_WAYPOINT,

	PALETTE_DOODAD_USE_THICKNESS,
	PALETTE_DOODAD_SLIDER,
	PALETTE_BRUSHSHAPE_SQUARE,
	PALETTE_BRUSHSHAPE_CIRCLE,

	PALETTE_TERRAIN_OPTIONAL_BORDER_TOOL,
	PALETTE_TERRAIN_ERASER,
	PALETTE_TERRAIN_REFRESH_TOOL,
	PALETTE_TERRAIN_NOLOGOUT_TOOL,
	PALETTE_TERRAIN_PZ_TOOL,

	PALETTE_CREATURE_TILESET_CHOICE,
	PALETTE_CREATURE_LISTBOX,
	PALETTE_CREATURE_SPAWN_RADIUS,
	PALETTE_CREATURE_SPAWN_AMOUNT,
	PALETTE_CREATURE_SPAWN_INTERVAL,

	PALETTE_TERRAIN_NORMAL_DOOR,
	PALETTE_TERRAIN_LOCKED_DOOR,
	PALETTE_TERRAIN_MAGIC_DOOR,
	PALETTE_TERRAIN_QUEST_DOOR,
	PALETTE_TERRAIN_HATCH_DOOR,
	PALETTE_TERRAIN_WINDOW_DOOR,

	PALETTE_TERRAIN_BRUSHSIZE_0,
	PALETTE_TERRAIN_BRUSHSIZE_1,
	PALETTE_TERRAIN_BRUSHSIZE_2,
	PALETTE_TERRAIN_BRUSHSIZE_4,
	PALETTE_TERRAIN_BRUSHSIZE_6,
	PALETTE_TERRAIN_BRUSHSIZE_8,
	PALETTE_TERRAIN_BRUSHSIZE_11,

	ITEM_PROPERTIES_GENERAL_TAB,
	ITEM_PROPERTIES_CONTAINER_TAB,
	ITEM_PROPERTIES_ADVANCED_TAB,

	ITEM_PROPERTIES_ADD_ATTRIBUTE,
	ITEM_PROPERTIES_REMOVE_ATTRIBUTE,

	ABOUT_RUN_TETRIS,
	ABOUT_RUN_SNAKE,
	ABOUT_VIEW_LICENSE,

	PANE_MAIN,
	PANE_PROPERTIES,
	PANE_ADVANCED_GRAPHICS,

	PALETTE_DELAYED_REFRESH_TIMER,
	PALETTE_LAYOUT_FIX_TIMER,

	TOOLBAR_POSITION_GO,
	TOOLBAR_SIZES_CIRCULAR,
	TOOLBAR_SIZES_RECTANGULAR,
	TOOLBAR_SIZES_1,
	TOOLBAR_SIZES_2,
	TOOLBAR_SIZES_3,
	TOOLBAR_SIZES_4,
	TOOLBAR_SIZES_5,
	TOOLBAR_SIZES_6,
	TOOLBAR_SIZES_7,
	TOOLBAR_HOOKS,
	TOOLBAR_PICKUPABLES,
	TOOLBAR_MOVEABLES
};

enum ToolBarID {
	TOOLBAR_STANDARD,
	TOOLBAR_BRUSHES,
	TOOLBAR_POSITION,
	TOOLBAR_SIZES,
	TOOLBAR_INDICATORS,
};

#endif
